name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  documentation:
    permissions:
      contents: read
      pages: write
      id-token: write
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev doxygen

      - name: Set up CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build -- -j

      - name: Run tests
        run: ./build/test_add

      - name: Run benchmarks
        run: ./build/benchmark_add --benchmark_format=json --benchmark_out=benchmark_results.json

      - name: Generate Doxygen documentation
        run: cmake --build build --target doc

      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./html

  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install doxygen
        run: sudo apt install doxygen && doxygen --version
      - name: Create documentation
        run: doxygen
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/html/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4